/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *notebook1;
  GtkWidget *fixed1;
  GtkWidget *label3;
  GtkWidget *id_client;
  GtkWidget *label4;
  GtkWidget *reclamation;
  GtkWidget *soumettre;
  GtkWidget *label5;
  GtkWidget *combobox_sujet;
  GtkWidget *label1;
  GtkWidget *fixed2;
  GtkWidget *treeview1;
  GtkWidget *afficher;
  GtkWidget *label6;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkWidget *modifier;
  GtkWidget *label2;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_container_add (GTK_CONTAINER (window1), notebook1);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed1);

  label3 = gtk_label_new (_("id_client"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 0, 24);
  gtk_widget_set_size_request (label3, 96, 33);

  id_client = gtk_entry_new ();
  gtk_widget_show (id_client);
  gtk_fixed_put (GTK_FIXED (fixed1), id_client, 80, 24);
  gtk_widget_set_size_request (id_client, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (id_client), 8226);

  label4 = gtk_label_new (_("sujet"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed1), label4, 24, 88);
  gtk_widget_set_size_request (label4, 41, 17);

  reclamation = gtk_entry_new ();
  gtk_widget_show (reclamation);
  gtk_fixed_put (GTK_FIXED (fixed1), reclamation, 136, 120);
  gtk_widget_set_size_request (reclamation, 112, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (reclamation), 8226);

  soumettre = gtk_button_new_with_mnemonic (_("soumettre"));
  gtk_widget_show (soumettre);
  gtk_fixed_put (GTK_FIXED (fixed1), soumettre, 160, 168);
  gtk_widget_set_size_request (soumettre, 104, 29);

  label5 = gtk_label_new (_("reclamation"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed1), label5, 0, 128);
  gtk_widget_set_size_request (label5, 136, 16);

  combobox_sujet = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_sujet);
  gtk_fixed_put (GTK_FIXED (fixed1), combobox_sujet, 80, 80);
  gtk_widget_set_size_request (combobox_sujet, 136, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_sujet), _("hotels"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_sujet), _("vols"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_sujet), _("hebergements"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_sujet), _("autres"));

  label1 = gtk_label_new (_("soumettre"));
  gtk_widget_show (label1);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label1);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed2);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed2), treeview1, 40, 40);
  gtk_widget_set_size_request (treeview1, 300, 200);

  afficher = gtk_button_new_with_mnemonic (_("afficher"));
  gtk_widget_show (afficher);
  gtk_fixed_put (GTK_FIXED (fixed2), afficher, 432, 56);
  gtk_widget_set_size_request (afficher, 66, 29);

  label6 = gtk_label_new (_("mes  reclamations"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed2), label6, 112, 16);
  gtk_widget_set_size_request (label6, 153, 16);

  spinbutton1_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton1, 352, 216);
  gtk_widget_set_size_request (spinbutton1, 60, 27);

  modifier = gtk_button_new_with_mnemonic (_("modifier"));
  gtk_widget_show (modifier);
  gtk_fixed_put (GTK_FIXED (fixed2), modifier, 432, 216);
  gtk_widget_set_size_request (modifier, 66, 29);

  label2 = gtk_label_new (_("afficher"));
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label2);

  g_signal_connect ((gpointer) soumettre, "clicked",
                    G_CALLBACK (on_soumettre_clicked),
                    NULL);
  g_signal_connect ((gpointer) afficher, "clicked",
                    G_CALLBACK (on_afficher_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifier, "clicked",
                    G_CALLBACK (on_modifier_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, label3, "label3");
  GLADE_HOOKUP_OBJECT (window1, id_client, "id_client");
  GLADE_HOOKUP_OBJECT (window1, label4, "label4");
  GLADE_HOOKUP_OBJECT (window1, reclamation, "reclamation");
  GLADE_HOOKUP_OBJECT (window1, soumettre, "soumettre");
  GLADE_HOOKUP_OBJECT (window1, label5, "label5");
  GLADE_HOOKUP_OBJECT (window1, combobox_sujet, "combobox_sujet");
  GLADE_HOOKUP_OBJECT (window1, label1, "label1");
  GLADE_HOOKUP_OBJECT (window1, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window1, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (window1, afficher, "afficher");
  GLADE_HOOKUP_OBJECT (window1, label6, "label6");
  GLADE_HOOKUP_OBJECT (window1, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (window1, modifier, "modifier");
  GLADE_HOOKUP_OBJECT (window1, label2, "label2");

  return window1;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *fixed5;
  GtkWidget *label11;
  GtkWidget *id_client;
  GtkWidget *label12;
  GtkWidget *reclamation;
  GtkWidget *button1;
  GtkWidget *label13;
  GtkWidget *combobox_sujet;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2), _("window2"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (window2), fixed5);

  label11 = gtk_label_new (_("id_client"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed5), label11, 0, 24);
  gtk_widget_set_size_request (label11, 96, 33);

  id_client = gtk_entry_new ();
  gtk_widget_show (id_client);
  gtk_fixed_put (GTK_FIXED (fixed5), id_client, 80, 24);
  gtk_widget_set_size_request (id_client, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (id_client), 8226);

  label12 = gtk_label_new (_("sujet"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed5), label12, 24, 88);
  gtk_widget_set_size_request (label12, 41, 17);

  reclamation = gtk_entry_new ();
  gtk_widget_show (reclamation);
  gtk_fixed_put (GTK_FIXED (fixed5), reclamation, 136, 120);
  gtk_widget_set_size_request (reclamation, 112, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (reclamation), 8226);

  button1 = gtk_button_new_with_mnemonic (_("soumettre"));
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed5), button1, 160, 168);
  gtk_widget_set_size_request (button1, 104, 29);

  label13 = gtk_label_new (_("reclamation"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed5), label13, 0, 128);
  gtk_widget_set_size_request (label13, 136, 16);

  combobox_sujet = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_sujet);
  gtk_fixed_put (GTK_FIXED (fixed5), combobox_sujet, 80, 80);
  gtk_widget_set_size_request (combobox_sujet, 136, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_sujet), _("hotels"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_sujet), _("vols"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_sujet), _("hebergements"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_sujet), _("autres"));

  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_soumettre_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window2, label11, "label11");
  GLADE_HOOKUP_OBJECT (window2, id_client, "id_client");
  GLADE_HOOKUP_OBJECT (window2, label12, "label12");
  GLADE_HOOKUP_OBJECT (window2, reclamation, "reclamation");
  GLADE_HOOKUP_OBJECT (window2, button1, "button1");
  GLADE_HOOKUP_OBJECT (window2, label13, "label13");
  GLADE_HOOKUP_OBJECT (window2, combobox_sujet, "combobox_sujet");

  return window2;
}

